### ISSUE TITLE
When to set shape for Input data?

### ISSUE THREAD

**Issue by EmbraceLife** [EmbraceLife/LIE#4]
Data is preprocessed (shape, norm, one-hot) in Data supplier, and then made batch through data provider. Then it seems that data is well prepared for training. 

Then why do we ever need to change the shape of Input data inside `Model: - input: `? 
```
model:
  - input:
      # when and how should I change data shape?
      shape: 100 #[28,28,1] # 100
    name: images
```

>   File "/Users/Natsume/Documents/kur/kur/containers/layers/placeholder.py", line 191, in _build
>     self._infer_shape(model)
>   File "/Users/Natsume/Documents/kur/kur/containers/layers/placeholder.py", line 139, in _infer_shape
>     .format(self.name, self._shape, inferred_shape))
> ValueError: Placeholder "images" does not have the same dimensionality as the data source it is connected to. Placeholder: (100,), data source: (28, 28, 1).
