### ISSUE TITLE
How to see training logic in detail steps?

### ISSUE THREAD

**Issue by EmbraceLife** [EmbraceLife/LIE#8]
Build a framework or template for training

**Comment by EmbraceLife** [comment]
The training logic description is done see [commit ](https://github.com/EmbraceLife/LIE/commit/6b9247e723e7b7257be5b50b5e3ed4a950273601)

To see the logic clearly, make sure to train the minimum  ( batch_size = num_as_you_need, num_batches = 1, epoch = 1, see below as example )

```yaml
train:
  data:
    - cifar:
        <<: *cifar
        parts: [1, 2, 3, 4]
  provider:
    batch_size: 32
    num_batches: 1
  log: cifar-log
  epochs:
    number: 2 # this number is lower priority than `epochs` below
    mode: additional
  stop_when:
    epochs: 1 # this number prioritize `epoch['number'] = 2` above
```

than run `kur train cifar.yaml`, then read the console for training logic details
